spring:
  profiles:
    active: development

  security:
    user:
      name: user
      password: user

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/automotive
    username: juanp
    password: abc123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  pattern:
    #console: "%d %-20level %logger : %msg%n"

server:
  port: 8080
